//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Retour_Article
    {
        public int br_A_ID { get; set; }
        public Nullable<System.DateTime> br_A_Date { get; set; }
        public Nullable<int> br_Qte_Livree { get; set; }
        public Nullable<int> br_ID { get; set; }
        public Nullable<int> pne_ID { get; set; }
        public string br_A_Description { get; set; }
        public Nullable<bool> br_A_Historique { get; set; }
    
        public virtual Bon_Retour Bon_Retour { get; set; }
        public virtual Pneu Pneu { get; set; }
    }
}
