//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bon_Entree_Article
    {
        public int be_A_ID { get; set; }
        public Nullable<System.DateTime> be_A_Date { get; set; }
        public Nullable<int> be_Qte_Livree { get; set; }
        public Nullable<int> be_ID { get; set; }
        public Nullable<int> pne_ID { get; set; }
        public string be_A_Description { get; set; }
        public Nullable<bool> be_A_Historique { get; set; }
    
        public virtual Bon_Entree Bon_Entree { get; set; }
        public virtual Pneu Pneu { get; set; }
    }
}
