//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GestionEntities : DbContext
    {
        public GestionEntities()
            : base("name=GestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pneu> Pneu { get; set; }
        public virtual DbSet<Bon_Entree> Bon_Entree { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Representant> Representant { get; set; }
        public virtual DbSet<Bon_Entree_Article> Bon_Entree_Article { get; set; }
        public virtual DbSet<Operation> Operation { get; set; }
        public virtual DbSet<Bon_Sortie> Bon_Sortie { get; set; }
        public virtual DbSet<Bon_Sortie_Article> Bon_Sortie_Article { get; set; }
        public virtual DbSet<Unite_Soutien> Unite_Soutien { get; set; }
        public virtual DbSet<Bon_Retour> Bon_Retour { get; set; }
        public virtual DbSet<Bon_Retour_Article> Bon_Retour_Article { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
    
        public virtual int Delete_Operation(Nullable<int> opera_ID)
        {
            var opera_IDParameter = opera_ID.HasValue ?
                new ObjectParameter("opera_ID", opera_ID) :
                new ObjectParameter("opera_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Operation", opera_IDParameter);
        }
    
        public virtual int Delete_Pneu(Nullable<int> pne_ID)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Pneu", pne_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Pneu(Nullable<int> pne_ID, string pne_Designation, string pne_Marque, Nullable<System.DateTime> pne_Date_Production, string pne_Observation)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var pne_DesignationParameter = pne_Designation != null ?
                new ObjectParameter("pne_Designation", pne_Designation) :
                new ObjectParameter("pne_Designation", typeof(string));
    
            var pne_MarqueParameter = pne_Marque != null ?
                new ObjectParameter("pne_Marque", pne_Marque) :
                new ObjectParameter("pne_Marque", typeof(string));
    
            var pne_Date_ProductionParameter = pne_Date_Production.HasValue ?
                new ObjectParameter("pne_Date_Production", pne_Date_Production) :
                new ObjectParameter("pne_Date_Production", typeof(System.DateTime));
    
            var pne_ObservationParameter = pne_Observation != null ?
                new ObjectParameter("pne_Observation", pne_Observation) :
                new ObjectParameter("pne_Observation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Pneu", pne_IDParameter, pne_DesignationParameter, pne_MarqueParameter, pne_Date_ProductionParameter, pne_ObservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Operation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Operation");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Pneu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Pneu");
        }
    
        public virtual ObjectResult<Select_Operation_By_Type_Result> Select_Operation_By_Type(Nullable<int> pne_ID, string opera_Type)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var opera_TypeParameter = opera_Type != null ?
                new ObjectParameter("opera_Type", opera_Type) :
                new ObjectParameter("opera_Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Operation_By_Type_Result>("Select_Operation_By_Type", pne_IDParameter, opera_TypeParameter);
        }
    
        public virtual ObjectResult<Select_Pneu_Result> Select_Pneu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Pneu_Result>("Select_Pneu");
        }
    
        public virtual ObjectResult<SommeQte_Result> SommeQte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SommeQte_Result>("SommeQte");
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Pneu(Nullable<int> pne_ID, string pne_Designation, string pne_Marque, Nullable<System.DateTime> pne_Date_Production, string pne_Observation)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var pne_DesignationParameter = pne_Designation != null ?
                new ObjectParameter("pne_Designation", pne_Designation) :
                new ObjectParameter("pne_Designation", typeof(string));
    
            var pne_MarqueParameter = pne_Marque != null ?
                new ObjectParameter("pne_Marque", pne_Marque) :
                new ObjectParameter("pne_Marque", typeof(string));
    
            var pne_Date_ProductionParameter = pne_Date_Production.HasValue ?
                new ObjectParameter("pne_Date_Production", pne_Date_Production) :
                new ObjectParameter("pne_Date_Production", typeof(System.DateTime));
    
            var pne_ObservationParameter = pne_Observation != null ?
                new ObjectParameter("pne_Observation", pne_Observation) :
                new ObjectParameter("pne_Observation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Pneu", pne_IDParameter, pne_DesignationParameter, pne_MarqueParameter, pne_Date_ProductionParameter, pne_ObservationParameter);
        }
    
        public virtual int Select_Operation_By_ID(Nullable<int> opera_ID)
        {
            var opera_IDParameter = opera_ID.HasValue ?
                new ObjectParameter("opera_ID", opera_ID) :
                new ObjectParameter("opera_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Select_Operation_By_ID", opera_IDParameter);
        }
    
        public virtual ObjectResult<Pneu> Show_Pneu_By_ID(Nullable<int> pne_ID)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pneu>("Show_Pneu_By_ID", pne_IDParameter);
        }
    
        public virtual ObjectResult<Pneu> Show_Pneu_By_ID(Nullable<int> pne_ID, MergeOption mergeOption)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pneu>("Show_Pneu_By_ID", mergeOption, pne_IDParameter);
        }
    
        public virtual int Delete_Bon_Entree(Nullable<int> be_ID)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Bon_Entree", be_IDParameter);
        }
    
        public virtual int Delete_Fournisseur(Nullable<int> frns_ID)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Fournisseur", frns_IDParameter);
        }
    
        public virtual int Delete_Representant(Nullable<int> rep_ID)
        {
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Representant", rep_IDParameter);
        }
    
        public virtual int Delete_Representant_All(Nullable<int> frns_ID)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Representant_All", frns_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Bon_Entree(Nullable<int> be_ID, Nullable<System.DateTime> be_Date, string be_Designation, string be_Reference, string be_PV, Nullable<int> frns_ID, Nullable<int> rep_ID, string be_Description)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            var be_DateParameter = be_Date.HasValue ?
                new ObjectParameter("be_Date", be_Date) :
                new ObjectParameter("be_Date", typeof(System.DateTime));
    
            var be_DesignationParameter = be_Designation != null ?
                new ObjectParameter("be_Designation", be_Designation) :
                new ObjectParameter("be_Designation", typeof(string));
    
            var be_ReferenceParameter = be_Reference != null ?
                new ObjectParameter("be_Reference", be_Reference) :
                new ObjectParameter("be_Reference", typeof(string));
    
            var be_PVParameter = be_PV != null ?
                new ObjectParameter("be_PV", be_PV) :
                new ObjectParameter("be_PV", typeof(string));
    
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            var be_DescriptionParameter = be_Description != null ?
                new ObjectParameter("be_Description", be_Description) :
                new ObjectParameter("be_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Bon_Entree", be_IDParameter, be_DateParameter, be_DesignationParameter, be_ReferenceParameter, be_PVParameter, frns_IDParameter, rep_IDParameter, be_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Fournisseur(Nullable<int> frns_ID, string frns_Nom, string frns_Adresse, string frns_Adresse2, string frns_Code_Postal, Nullable<int> vil_ID, string frns_Email, string frns_GSM, string frns_GSM2, string frns_Fixe1, string frns_Fixe2, string frns_Description)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            var frns_NomParameter = frns_Nom != null ?
                new ObjectParameter("frns_Nom", frns_Nom) :
                new ObjectParameter("frns_Nom", typeof(string));
    
            var frns_AdresseParameter = frns_Adresse != null ?
                new ObjectParameter("frns_Adresse", frns_Adresse) :
                new ObjectParameter("frns_Adresse", typeof(string));
    
            var frns_Adresse2Parameter = frns_Adresse2 != null ?
                new ObjectParameter("frns_Adresse2", frns_Adresse2) :
                new ObjectParameter("frns_Adresse2", typeof(string));
    
            var frns_Code_PostalParameter = frns_Code_Postal != null ?
                new ObjectParameter("frns_Code_Postal", frns_Code_Postal) :
                new ObjectParameter("frns_Code_Postal", typeof(string));
    
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            var frns_EmailParameter = frns_Email != null ?
                new ObjectParameter("frns_Email", frns_Email) :
                new ObjectParameter("frns_Email", typeof(string));
    
            var frns_GSMParameter = frns_GSM != null ?
                new ObjectParameter("frns_GSM", frns_GSM) :
                new ObjectParameter("frns_GSM", typeof(string));
    
            var frns_GSM2Parameter = frns_GSM2 != null ?
                new ObjectParameter("frns_GSM2", frns_GSM2) :
                new ObjectParameter("frns_GSM2", typeof(string));
    
            var frns_Fixe1Parameter = frns_Fixe1 != null ?
                new ObjectParameter("frns_Fixe1", frns_Fixe1) :
                new ObjectParameter("frns_Fixe1", typeof(string));
    
            var frns_Fixe2Parameter = frns_Fixe2 != null ?
                new ObjectParameter("frns_Fixe2", frns_Fixe2) :
                new ObjectParameter("frns_Fixe2", typeof(string));
    
            var frns_DescriptionParameter = frns_Description != null ?
                new ObjectParameter("frns_Description", frns_Description) :
                new ObjectParameter("frns_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Fournisseur", frns_IDParameter, frns_NomParameter, frns_AdresseParameter, frns_Adresse2Parameter, frns_Code_PostalParameter, vil_IDParameter, frns_EmailParameter, frns_GSMParameter, frns_GSM2Parameter, frns_Fixe1Parameter, frns_Fixe2Parameter, frns_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Representant(Nullable<int> rep_ID, Nullable<int> frns_ID, string rep_Nom, string rep_Prenom, string rep_Cin, string rep_Tele, string rep_Observation)
        {
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            var rep_NomParameter = rep_Nom != null ?
                new ObjectParameter("rep_Nom", rep_Nom) :
                new ObjectParameter("rep_Nom", typeof(string));
    
            var rep_PrenomParameter = rep_Prenom != null ?
                new ObjectParameter("rep_Prenom", rep_Prenom) :
                new ObjectParameter("rep_Prenom", typeof(string));
    
            var rep_CinParameter = rep_Cin != null ?
                new ObjectParameter("rep_Cin", rep_Cin) :
                new ObjectParameter("rep_Cin", typeof(string));
    
            var rep_TeleParameter = rep_Tele != null ?
                new ObjectParameter("rep_Tele", rep_Tele) :
                new ObjectParameter("rep_Tele", typeof(string));
    
            var rep_ObservationParameter = rep_Observation != null ?
                new ObjectParameter("rep_Observation", rep_Observation) :
                new ObjectParameter("rep_Observation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Representant", rep_IDParameter, frns_IDParameter, rep_NomParameter, rep_PrenomParameter, rep_CinParameter, rep_TeleParameter, rep_ObservationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Bon_Entree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Bon_Entree");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Fournisseur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Fournisseur");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Representant()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Representant");
        }
    
        public virtual ObjectResult<Select_Bon_Entree_Result> Select_Bon_Entree()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Bon_Entree_Result>("Select_Bon_Entree");
        }
    
        public virtual ObjectResult<Select_Bon_Entree_Article_Result> Select_Bon_Entree_Article(Nullable<int> be_ID)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Bon_Entree_Article_Result>("Select_Bon_Entree_Article", be_IDParameter);
        }
    
        public virtual ObjectResult<Select_Fournisseur_Result> Select_Fournisseur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Fournisseur_Result>("Select_Fournisseur");
        }
    
        public virtual ObjectResult<Select_Representant_Result> Select_Representant(Nullable<int> frns_ID)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Representant_Result>("Select_Representant", frns_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Bon_Entree(Nullable<int> be_ID, Nullable<System.DateTime> be_Date, string be_Designation, string be_Reference, string be_PV, Nullable<int> frns_ID, Nullable<int> rep_ID, string be_Description)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            var be_DateParameter = be_Date.HasValue ?
                new ObjectParameter("be_Date", be_Date) :
                new ObjectParameter("be_Date", typeof(System.DateTime));
    
            var be_DesignationParameter = be_Designation != null ?
                new ObjectParameter("be_Designation", be_Designation) :
                new ObjectParameter("be_Designation", typeof(string));
    
            var be_ReferenceParameter = be_Reference != null ?
                new ObjectParameter("be_Reference", be_Reference) :
                new ObjectParameter("be_Reference", typeof(string));
    
            var be_PVParameter = be_PV != null ?
                new ObjectParameter("be_PV", be_PV) :
                new ObjectParameter("be_PV", typeof(string));
    
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            var be_DescriptionParameter = be_Description != null ?
                new ObjectParameter("be_Description", be_Description) :
                new ObjectParameter("be_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Bon_Entree", be_IDParameter, be_DateParameter, be_DesignationParameter, be_ReferenceParameter, be_PVParameter, frns_IDParameter, rep_IDParameter, be_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Fournisseur(Nullable<int> frns_ID, string frns_Nom, string frns_Adresse, string frns_Adresse2, string frns_Code_Postal, Nullable<int> vil_ID, string frns_Email, string frns_GSM, string frns_GSM2, string frns_Fixe1, string frns_Fixe2, string frns_Description)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            var frns_NomParameter = frns_Nom != null ?
                new ObjectParameter("frns_Nom", frns_Nom) :
                new ObjectParameter("frns_Nom", typeof(string));
    
            var frns_AdresseParameter = frns_Adresse != null ?
                new ObjectParameter("frns_Adresse", frns_Adresse) :
                new ObjectParameter("frns_Adresse", typeof(string));
    
            var frns_Adresse2Parameter = frns_Adresse2 != null ?
                new ObjectParameter("frns_Adresse2", frns_Adresse2) :
                new ObjectParameter("frns_Adresse2", typeof(string));
    
            var frns_Code_PostalParameter = frns_Code_Postal != null ?
                new ObjectParameter("frns_Code_Postal", frns_Code_Postal) :
                new ObjectParameter("frns_Code_Postal", typeof(string));
    
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            var frns_EmailParameter = frns_Email != null ?
                new ObjectParameter("frns_Email", frns_Email) :
                new ObjectParameter("frns_Email", typeof(string));
    
            var frns_GSMParameter = frns_GSM != null ?
                new ObjectParameter("frns_GSM", frns_GSM) :
                new ObjectParameter("frns_GSM", typeof(string));
    
            var frns_GSM2Parameter = frns_GSM2 != null ?
                new ObjectParameter("frns_GSM2", frns_GSM2) :
                new ObjectParameter("frns_GSM2", typeof(string));
    
            var frns_Fixe1Parameter = frns_Fixe1 != null ?
                new ObjectParameter("frns_Fixe1", frns_Fixe1) :
                new ObjectParameter("frns_Fixe1", typeof(string));
    
            var frns_Fixe2Parameter = frns_Fixe2 != null ?
                new ObjectParameter("frns_Fixe2", frns_Fixe2) :
                new ObjectParameter("frns_Fixe2", typeof(string));
    
            var frns_DescriptionParameter = frns_Description != null ?
                new ObjectParameter("frns_Description", frns_Description) :
                new ObjectParameter("frns_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Fournisseur", frns_IDParameter, frns_NomParameter, frns_AdresseParameter, frns_Adresse2Parameter, frns_Code_PostalParameter, vil_IDParameter, frns_EmailParameter, frns_GSMParameter, frns_GSM2Parameter, frns_Fixe1Parameter, frns_Fixe2Parameter, frns_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Representant(Nullable<int> rep_ID, Nullable<int> frns_ID, string rep_Nom, string rep_Prenom, string rep_Cin, string rep_Tele, string rep_Observation)
        {
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            var rep_NomParameter = rep_Nom != null ?
                new ObjectParameter("rep_Nom", rep_Nom) :
                new ObjectParameter("rep_Nom", typeof(string));
    
            var rep_PrenomParameter = rep_Prenom != null ?
                new ObjectParameter("rep_Prenom", rep_Prenom) :
                new ObjectParameter("rep_Prenom", typeof(string));
    
            var rep_CinParameter = rep_Cin != null ?
                new ObjectParameter("rep_Cin", rep_Cin) :
                new ObjectParameter("rep_Cin", typeof(string));
    
            var rep_TeleParameter = rep_Tele != null ?
                new ObjectParameter("rep_Tele", rep_Tele) :
                new ObjectParameter("rep_Tele", typeof(string));
    
            var rep_ObservationParameter = rep_Observation != null ?
                new ObjectParameter("rep_Observation", rep_Observation) :
                new ObjectParameter("rep_Observation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Representant", rep_IDParameter, frns_IDParameter, rep_NomParameter, rep_PrenomParameter, rep_CinParameter, rep_TeleParameter, rep_ObservationParameter);
        }
    
        public virtual ObjectResult<Bon_Entree> Show_Bon_Entree_By_ID(Nullable<int> be_ID)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Entree>("Show_Bon_Entree_By_ID", be_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Entree> Show_Bon_Entree_By_ID(Nullable<int> be_ID, MergeOption mergeOption)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Entree>("Show_Bon_Entree_By_ID", mergeOption, be_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Entree_Article> Show_Bon_Entree_Article_By_ID(Nullable<int> be_A_ID)
        {
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Entree_Article>("Show_Bon_Entree_Article_By_ID", be_A_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Entree_Article> Show_Bon_Entree_Article_By_ID(Nullable<int> be_A_ID, MergeOption mergeOption)
        {
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Entree_Article>("Show_Bon_Entree_Article_By_ID", mergeOption, be_A_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Bon_Entree_Article()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Bon_Entree_Article");
        }
    
        public virtual int Delete_Bon_Entree_Article(Nullable<int> be_A_ID)
        {
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Bon_Entree_Article", be_A_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Bon_Entree_Article(Nullable<int> be_A_ID, Nullable<System.DateTime> be_A_Date, Nullable<int> be_Qte_Livree, Nullable<int> be_ID, Nullable<int> pne_ID, string be_A_Description)
        {
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            var be_A_DateParameter = be_A_Date.HasValue ?
                new ObjectParameter("be_A_Date", be_A_Date) :
                new ObjectParameter("be_A_Date", typeof(System.DateTime));
    
            var be_Qte_LivreeParameter = be_Qte_Livree.HasValue ?
                new ObjectParameter("be_Qte_Livree", be_Qte_Livree) :
                new ObjectParameter("be_Qte_Livree", typeof(int));
    
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var be_A_DescriptionParameter = be_A_Description != null ?
                new ObjectParameter("be_A_Description", be_A_Description) :
                new ObjectParameter("be_A_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Bon_Entree_Article", be_A_IDParameter, be_A_DateParameter, be_Qte_LivreeParameter, be_IDParameter, pne_IDParameter, be_A_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Bon_Entree_Article(Nullable<int> be_A_ID, Nullable<System.DateTime> be_A_Date, Nullable<int> be_Qte_Livree, Nullable<int> be_ID, Nullable<int> pne_ID, string be_A_Description)
        {
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            var be_A_DateParameter = be_A_Date.HasValue ?
                new ObjectParameter("be_A_Date", be_A_Date) :
                new ObjectParameter("be_A_Date", typeof(System.DateTime));
    
            var be_Qte_LivreeParameter = be_Qte_Livree.HasValue ?
                new ObjectParameter("be_Qte_Livree", be_Qte_Livree) :
                new ObjectParameter("be_Qte_Livree", typeof(int));
    
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var be_A_DescriptionParameter = be_A_Description != null ?
                new ObjectParameter("be_A_Description", be_A_Description) :
                new ObjectParameter("be_A_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Bon_Entree_Article", be_A_IDParameter, be_A_DateParameter, be_Qte_LivreeParameter, be_IDParameter, pne_IDParameter, be_A_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Operation(Nullable<int> opera_ID, Nullable<System.DateTime> opera_Date, Nullable<int> pne_ID, string opera_Type, Nullable<int> opera_Qte, Nullable<int> bon_ID, Nullable<int> bs_A_ID, Nullable<int> be_A_ID, Nullable<int> br_A_ID)
        {
            var opera_IDParameter = opera_ID.HasValue ?
                new ObjectParameter("opera_ID", opera_ID) :
                new ObjectParameter("opera_ID", typeof(int));
    
            var opera_DateParameter = opera_Date.HasValue ?
                new ObjectParameter("opera_Date", opera_Date) :
                new ObjectParameter("opera_Date", typeof(System.DateTime));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var opera_TypeParameter = opera_Type != null ?
                new ObjectParameter("opera_Type", opera_Type) :
                new ObjectParameter("opera_Type", typeof(string));
    
            var opera_QteParameter = opera_Qte.HasValue ?
                new ObjectParameter("opera_Qte", opera_Qte) :
                new ObjectParameter("opera_Qte", typeof(int));
    
            var bon_IDParameter = bon_ID.HasValue ?
                new ObjectParameter("bon_ID", bon_ID) :
                new ObjectParameter("bon_ID", typeof(int));
    
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Operation", opera_IDParameter, opera_DateParameter, pne_IDParameter, opera_TypeParameter, opera_QteParameter, bon_IDParameter, bs_A_IDParameter, be_A_IDParameter, br_A_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Operation(Nullable<int> opera_ID, Nullable<System.DateTime> opera_Date, Nullable<int> pne_ID, string opera_Type, Nullable<int> opera_Qte, Nullable<int> bon_ID, Nullable<int> bs_A_ID, Nullable<int> be_A_ID, Nullable<int> br_A_ID)
        {
            var opera_IDParameter = opera_ID.HasValue ?
                new ObjectParameter("opera_ID", opera_ID) :
                new ObjectParameter("opera_ID", typeof(int));
    
            var opera_DateParameter = opera_Date.HasValue ?
                new ObjectParameter("opera_Date", opera_Date) :
                new ObjectParameter("opera_Date", typeof(System.DateTime));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var opera_TypeParameter = opera_Type != null ?
                new ObjectParameter("opera_Type", opera_Type) :
                new ObjectParameter("opera_Type", typeof(string));
    
            var opera_QteParameter = opera_Qte.HasValue ?
                new ObjectParameter("opera_Qte", opera_Qte) :
                new ObjectParameter("opera_Qte", typeof(int));
    
            var bon_IDParameter = bon_ID.HasValue ?
                new ObjectParameter("bon_ID", bon_ID) :
                new ObjectParameter("bon_ID", typeof(int));
    
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Operation", opera_IDParameter, opera_DateParameter, pne_IDParameter, opera_TypeParameter, opera_QteParameter, bon_IDParameter, bs_A_IDParameter, be_A_IDParameter, br_A_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Historique_Bon_Entree(Nullable<int> be_ID)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Historique_Bon_Entree", be_IDParameter);
        }
    
        public virtual int Delete_Bon_Sortie(Nullable<int> bs_ID)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Bon_Sortie", bs_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Bon_Sortie(Nullable<int> bs_ID, Nullable<System.DateTime> bs_Date, string bs_Designation, string bs_Reference, Nullable<int> unt_ID, string bs_Description)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            var bs_DateParameter = bs_Date.HasValue ?
                new ObjectParameter("bs_Date", bs_Date) :
                new ObjectParameter("bs_Date", typeof(System.DateTime));
    
            var bs_DesignationParameter = bs_Designation != null ?
                new ObjectParameter("bs_Designation", bs_Designation) :
                new ObjectParameter("bs_Designation", typeof(string));
    
            var bs_ReferenceParameter = bs_Reference != null ?
                new ObjectParameter("bs_Reference", bs_Reference) :
                new ObjectParameter("bs_Reference", typeof(string));
    
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            var bs_DescriptionParameter = bs_Description != null ?
                new ObjectParameter("bs_Description", bs_Description) :
                new ObjectParameter("bs_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Bon_Sortie", bs_IDParameter, bs_DateParameter, bs_DesignationParameter, bs_ReferenceParameter, unt_IDParameter, bs_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Bon_Sortie_Article(Nullable<int> bs_A_ID, Nullable<System.DateTime> bs_A_Date, Nullable<int> bs_Qte_Livree, Nullable<int> bs_ID, Nullable<int> pne_ID, string bs_A_Description)
        {
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            var bs_A_DateParameter = bs_A_Date.HasValue ?
                new ObjectParameter("bs_A_Date", bs_A_Date) :
                new ObjectParameter("bs_A_Date", typeof(System.DateTime));
    
            var bs_Qte_LivreeParameter = bs_Qte_Livree.HasValue ?
                new ObjectParameter("bs_Qte_Livree", bs_Qte_Livree) :
                new ObjectParameter("bs_Qte_Livree", typeof(int));
    
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var bs_A_DescriptionParameter = bs_A_Description != null ?
                new ObjectParameter("bs_A_Description", bs_A_Description) :
                new ObjectParameter("bs_A_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Bon_Sortie_Article", bs_A_IDParameter, bs_A_DateParameter, bs_Qte_LivreeParameter, bs_IDParameter, pne_IDParameter, bs_A_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Bon_Sortie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Bon_Sortie");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Bon_Sortie_Article()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Bon_Sortie_Article");
        }
    
        public virtual ObjectResult<Select_Bon_Sortie_Result> Select_Bon_Sortie()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Bon_Sortie_Result>("Select_Bon_Sortie");
        }
    
        public virtual ObjectResult<Select_Bon_Sortie_Article_Result> Select_Bon_Sortie_Article(Nullable<int> bs_ID)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Bon_Sortie_Article_Result>("Select_Bon_Sortie_Article", bs_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Bon_Sortie(Nullable<int> bs_ID, Nullable<System.DateTime> bs_Date, string bs_Designation, string bs_Reference, Nullable<int> unt_ID, string bs_Description)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            var bs_DateParameter = bs_Date.HasValue ?
                new ObjectParameter("bs_Date", bs_Date) :
                new ObjectParameter("bs_Date", typeof(System.DateTime));
    
            var bs_DesignationParameter = bs_Designation != null ?
                new ObjectParameter("bs_Designation", bs_Designation) :
                new ObjectParameter("bs_Designation", typeof(string));
    
            var bs_ReferenceParameter = bs_Reference != null ?
                new ObjectParameter("bs_Reference", bs_Reference) :
                new ObjectParameter("bs_Reference", typeof(string));
    
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            var bs_DescriptionParameter = bs_Description != null ?
                new ObjectParameter("bs_Description", bs_Description) :
                new ObjectParameter("bs_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Bon_Sortie", bs_IDParameter, bs_DateParameter, bs_DesignationParameter, bs_ReferenceParameter, unt_IDParameter, bs_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Bon_Sortie_Article(Nullable<int> bs_A_ID, Nullable<System.DateTime> bs_A_Date, Nullable<int> bs_Qte_Livree, Nullable<int> bs_ID, Nullable<int> pne_ID, string bs_A_Description)
        {
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            var bs_A_DateParameter = bs_A_Date.HasValue ?
                new ObjectParameter("bs_A_Date", bs_A_Date) :
                new ObjectParameter("bs_A_Date", typeof(System.DateTime));
    
            var bs_Qte_LivreeParameter = bs_Qte_Livree.HasValue ?
                new ObjectParameter("bs_Qte_Livree", bs_Qte_Livree) :
                new ObjectParameter("bs_Qte_Livree", typeof(int));
    
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var bs_A_DescriptionParameter = bs_A_Description != null ?
                new ObjectParameter("bs_A_Description", bs_A_Description) :
                new ObjectParameter("bs_A_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Bon_Sortie_Article", bs_A_IDParameter, bs_A_DateParameter, bs_Qte_LivreeParameter, bs_IDParameter, pne_IDParameter, bs_A_DescriptionParameter);
        }
    
        public virtual ObjectResult<Bon_Sortie_Article> Show_Bon_Sortie_Article_By_ID(Nullable<int> bs_A_ID)
        {
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Sortie_Article>("Show_Bon_Sortie_Article_By_ID", bs_A_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Sortie_Article> Show_Bon_Sortie_Article_By_ID(Nullable<int> bs_A_ID, MergeOption mergeOption)
        {
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Sortie_Article>("Show_Bon_Sortie_Article_By_ID", mergeOption, bs_A_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Sortie> Show_Bon_Sortie_By_ID(Nullable<int> bs_ID)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Sortie>("Show_Bon_Sortie_By_ID", bs_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Sortie> Show_Bon_Sortie_By_ID(Nullable<int> bs_ID, MergeOption mergeOption)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Sortie>("Show_Bon_Sortie_By_ID", mergeOption, bs_IDParameter);
        }
    
        public virtual ObjectResult<Historique_Bon_Entree_Article_H_Result> Historique_Bon_Entree_Article_H(Nullable<int> be_ID)
        {
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historique_Bon_Entree_Article_H_Result>("Historique_Bon_Entree_Article_H", be_IDParameter);
        }
    
        public virtual ObjectResult<Historique_Bon_Entree_H_Result> Historique_Bon_Entree_H()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historique_Bon_Entree_H_Result>("Historique_Bon_Entree_H");
        }
    
        public virtual ObjectResult<Historique_Bon_Sortie_Article_H_Result> Historique_Bon_Sortie_Article_H(Nullable<int> bs_ID)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historique_Bon_Sortie_Article_H_Result>("Historique_Bon_Sortie_Article_H", bs_IDParameter);
        }
    
        public virtual ObjectResult<Historique_Bon_Sortie_H_Result> Historique_Bon_Sortie_H()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historique_Bon_Sortie_H_Result>("Historique_Bon_Sortie_H");
        }
    
        public virtual ObjectResult<Nullable<int>> Historique_Bon_Sortie(Nullable<int> bs_ID)
        {
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Historique_Bon_Sortie", bs_IDParameter);
        }
    
        public virtual int Historique_Bon_Sortie_Article(Nullable<int> bs_A_ID)
        {
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Historique_Bon_Sortie_Article", bs_A_IDParameter);
        }
    
        public virtual int Delete_Bon_Sortie_Article(Nullable<int> bs_A_ID)
        {
            var bs_A_IDParameter = bs_A_ID.HasValue ?
                new ObjectParameter("bs_A_ID", bs_A_ID) :
                new ObjectParameter("bs_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Bon_Sortie_Article", bs_A_IDParameter);
        }
    
        public virtual ObjectResult<Select_Unite_Soutien_Result> Select_Unite_Soutien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Unite_Soutien_Result>("Select_Unite_Soutien");
        }
    
        public virtual ObjectResult<Nullable<int>> ResteQteArticle(Nullable<int> pne_ID)
        {
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ResteQteArticle", pne_IDParameter);
        }
    
        public virtual int Delete_Bon_Retour(Nullable<int> br_ID)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Bon_Retour", br_IDParameter);
        }
    
        public virtual int Delete_Bon_Retour_Article(Nullable<int> br_A_ID)
        {
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Bon_Retour_Article", br_A_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Historique_Bon_Retour(Nullable<int> br_ID)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Historique_Bon_Retour", br_IDParameter);
        }
    
        public virtual int Historique_Bon_Retour_Article(Nullable<int> br_A_ID)
        {
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Historique_Bon_Retour_Article", br_A_IDParameter);
        }
    
        public virtual ObjectResult<Historique_Bon_Retour_Article_H_Result> Historique_Bon_Retour_Article_H(Nullable<int> br_ID)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historique_Bon_Retour_Article_H_Result>("Historique_Bon_Retour_Article_H", br_IDParameter);
        }
    
        public virtual ObjectResult<Historique_Bon_Retour_H_Result> Historique_Bon_Retour_H()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Historique_Bon_Retour_H_Result>("Historique_Bon_Retour_H");
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Bon_Retour(Nullable<int> br_ID, Nullable<System.DateTime> br_Date, string br_Designation, string br_Reference, string br_PV, Nullable<int> unt_ID, string br_Description)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            var br_DateParameter = br_Date.HasValue ?
                new ObjectParameter("br_Date", br_Date) :
                new ObjectParameter("br_Date", typeof(System.DateTime));
    
            var br_DesignationParameter = br_Designation != null ?
                new ObjectParameter("br_Designation", br_Designation) :
                new ObjectParameter("br_Designation", typeof(string));
    
            var br_ReferenceParameter = br_Reference != null ?
                new ObjectParameter("br_Reference", br_Reference) :
                new ObjectParameter("br_Reference", typeof(string));
    
            var br_PVParameter = br_PV != null ?
                new ObjectParameter("br_PV", br_PV) :
                new ObjectParameter("br_PV", typeof(string));
    
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            var br_DescriptionParameter = br_Description != null ?
                new ObjectParameter("br_Description", br_Description) :
                new ObjectParameter("br_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Bon_Retour", br_IDParameter, br_DateParameter, br_DesignationParameter, br_ReferenceParameter, br_PVParameter, unt_IDParameter, br_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Bon_Retour()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Bon_Retour");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Bon_Retour_Article()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Bon_Retour_Article");
        }
    
        public virtual ObjectResult<Select_Bon_Retour_Result> Select_Bon_Retour()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Bon_Retour_Result>("Select_Bon_Retour");
        }
    
        public virtual ObjectResult<Select_Bon_Retour_Article_Result> Select_Bon_Retour_Article(Nullable<int> br_ID)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Bon_Retour_Article_Result>("Select_Bon_Retour_Article", br_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Bon_Retour(Nullable<int> br_ID, Nullable<System.DateTime> br_Date, string br_Designation, string br_Reference, string br_PV, Nullable<int> unt_ID, string br_Description)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            var br_DateParameter = br_Date.HasValue ?
                new ObjectParameter("br_Date", br_Date) :
                new ObjectParameter("br_Date", typeof(System.DateTime));
    
            var br_DesignationParameter = br_Designation != null ?
                new ObjectParameter("br_Designation", br_Designation) :
                new ObjectParameter("br_Designation", typeof(string));
    
            var br_ReferenceParameter = br_Reference != null ?
                new ObjectParameter("br_Reference", br_Reference) :
                new ObjectParameter("br_Reference", typeof(string));
    
            var br_PVParameter = br_PV != null ?
                new ObjectParameter("br_PV", br_PV) :
                new ObjectParameter("br_PV", typeof(string));
    
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            var br_DescriptionParameter = br_Description != null ?
                new ObjectParameter("br_Description", br_Description) :
                new ObjectParameter("br_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Bon_Retour", br_IDParameter, br_DateParameter, br_DesignationParameter, br_ReferenceParameter, br_PVParameter, unt_IDParameter, br_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Bon_Retour_Article(Nullable<int> br_A_ID, Nullable<System.DateTime> br_A_Date, Nullable<int> br_Qte_Livree, Nullable<int> br_ID, Nullable<int> pne_ID, string br_A_Description)
        {
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            var br_A_DateParameter = br_A_Date.HasValue ?
                new ObjectParameter("br_A_Date", br_A_Date) :
                new ObjectParameter("br_A_Date", typeof(System.DateTime));
    
            var br_Qte_LivreeParameter = br_Qte_Livree.HasValue ?
                new ObjectParameter("br_Qte_Livree", br_Qte_Livree) :
                new ObjectParameter("br_Qte_Livree", typeof(int));
    
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var br_A_DescriptionParameter = br_A_Description != null ?
                new ObjectParameter("br_A_Description", br_A_Description) :
                new ObjectParameter("br_A_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Bon_Retour_Article", br_A_IDParameter, br_A_DateParameter, br_Qte_LivreeParameter, br_IDParameter, pne_IDParameter, br_A_DescriptionParameter);
        }
    
        public virtual ObjectResult<Bon_Retour_Article> Show_Bon_Retour_Article_By_ID(Nullable<int> br_A_ID)
        {
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Retour_Article>("Show_Bon_Retour_Article_By_ID", br_A_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Retour_Article> Show_Bon_Retour_Article_By_ID(Nullable<int> br_A_ID, MergeOption mergeOption)
        {
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Retour_Article>("Show_Bon_Retour_Article_By_ID", mergeOption, br_A_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Retour> Show_Bon_Retour_By_ID(Nullable<int> br_ID)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Retour>("Show_Bon_Retour_By_ID", br_IDParameter);
        }
    
        public virtual ObjectResult<Bon_Retour> Show_Bon_Retour_By_ID(Nullable<int> br_ID, MergeOption mergeOption)
        {
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bon_Retour>("Show_Bon_Retour_By_ID", mergeOption, br_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Bon_Retour_Article(Nullable<int> br_A_ID, Nullable<System.DateTime> br_A_Date, Nullable<int> br_Qte_Livree, Nullable<int> br_ID, Nullable<int> pne_ID, string br_A_Description)
        {
            var br_A_IDParameter = br_A_ID.HasValue ?
                new ObjectParameter("br_A_ID", br_A_ID) :
                new ObjectParameter("br_A_ID", typeof(int));
    
            var br_A_DateParameter = br_A_Date.HasValue ?
                new ObjectParameter("br_A_Date", br_A_Date) :
                new ObjectParameter("br_A_Date", typeof(System.DateTime));
    
            var br_Qte_LivreeParameter = br_Qte_Livree.HasValue ?
                new ObjectParameter("br_Qte_Livree", br_Qte_Livree) :
                new ObjectParameter("br_Qte_Livree", typeof(int));
    
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            var pne_IDParameter = pne_ID.HasValue ?
                new ObjectParameter("pne_ID", pne_ID) :
                new ObjectParameter("pne_ID", typeof(int));
    
            var br_A_DescriptionParameter = br_A_Description != null ?
                new ObjectParameter("br_A_Description", br_A_Description) :
                new ObjectParameter("br_A_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Bon_Retour_Article", br_A_IDParameter, br_A_DateParameter, br_Qte_LivreeParameter, br_IDParameter, pne_IDParameter, br_A_DescriptionParameter);
        }
    
        public virtual ObjectResult<Select_Operation_By_Operation_Result> Select_Operation_By_Operation(string typeBon, string pne_Designation)
        {
            var typeBonParameter = typeBon != null ?
                new ObjectParameter("TypeBon", typeBon) :
                new ObjectParameter("TypeBon", typeof(string));
    
            var pne_DesignationParameter = pne_Designation != null ?
                new ObjectParameter("pne_Designation", pne_Designation) :
                new ObjectParameter("pne_Designation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Operation_By_Operation_Result>("Select_Operation_By_Operation", typeBonParameter, pne_DesignationParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Fournisseur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Fournisseur");
        }
    
        public virtual int Search_Fournisseur(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Search_Fournisseur", searchParameter);
        }
    
        public virtual ObjectResult<Search_Representant_Result> Search_Representant(string search, Nullable<int> frns_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Representant_Result>("Search_Representant", searchParameter, frns_IDParameter);
        }
    
        public virtual ObjectResult<Fournisseur> Show_Fournisseur_By_ID(Nullable<int> frns_ID)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fournisseur>("Show_Fournisseur_By_ID", frns_IDParameter);
        }
    
        public virtual ObjectResult<Fournisseur> Show_Fournisseur_By_ID(Nullable<int> frns_ID, MergeOption mergeOption)
        {
            var frns_IDParameter = frns_ID.HasValue ?
                new ObjectParameter("frns_ID", frns_ID) :
                new ObjectParameter("frns_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fournisseur>("Show_Fournisseur_By_ID", mergeOption, frns_IDParameter);
        }
    
        public virtual ObjectResult<Representant> Show_Representant_By_ID(Nullable<int> rep_ID)
        {
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Representant>("Show_Representant_By_ID", rep_IDParameter);
        }
    
        public virtual ObjectResult<Representant> Show_Representant_By_ID(Nullable<int> rep_ID, MergeOption mergeOption)
        {
            var rep_IDParameter = rep_ID.HasValue ?
                new ObjectParameter("rep_ID", rep_ID) :
                new ObjectParameter("rep_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Representant>("Show_Representant_By_ID", mergeOption, rep_IDParameter);
        }
    
        public virtual int Delete_Ville(Nullable<int> vil_ID)
        {
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Ville", vil_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Ville(Nullable<int> vil_ID, string vil_Nom, string vil_Description)
        {
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            var vil_NomParameter = vil_Nom != null ?
                new ObjectParameter("vil_Nom", vil_Nom) :
                new ObjectParameter("vil_Nom", typeof(string));
    
            var vil_DescriptionParameter = vil_Description != null ?
                new ObjectParameter("vil_Description", vil_Description) :
                new ObjectParameter("vil_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Ville", vil_IDParameter, vil_NomParameter, vil_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Ville()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Ville");
        }
    
        public virtual ObjectResult<Search_Ville_Result> Search_Ville(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Ville_Result>("Search_Ville", searchParameter);
        }
    
        public virtual ObjectResult<Select_Ville_Result> Select_Ville()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Ville_Result>("Select_Ville");
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Ville(Nullable<int> vil_ID, string vil_Nom, string vil_Description)
        {
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            var vil_NomParameter = vil_Nom != null ?
                new ObjectParameter("vil_Nom", vil_Nom) :
                new ObjectParameter("vil_Nom", typeof(string));
    
            var vil_DescriptionParameter = vil_Description != null ?
                new ObjectParameter("vil_Description", vil_Description) :
                new ObjectParameter("vil_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Ville", vil_IDParameter, vil_NomParameter, vil_DescriptionParameter);
        }
    
        public virtual ObjectResult<Ville> Show_Ville_By_ID(Nullable<int> vil_ID)
        {
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ville>("Show_Ville_By_ID", vil_IDParameter);
        }
    
        public virtual ObjectResult<Ville> Show_Ville_By_ID(Nullable<int> vil_ID, MergeOption mergeOption)
        {
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Ville>("Show_Ville_By_ID", mergeOption, vil_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Ville()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Ville");
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Unite_Soutien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Unite_Soutien");
        }
    
        public virtual int Delete_Unite_Soutien(Nullable<int> unt_ID)
        {
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Unite_Soutien", unt_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Insert_Unite_Soutien(Nullable<int> unt_ID, string unt_Unite, Nullable<int> vil_ID, string unt_Description)
        {
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            var unt_UniteParameter = unt_Unite != null ?
                new ObjectParameter("unt_Unite", unt_Unite) :
                new ObjectParameter("unt_Unite", typeof(string));
    
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            var unt_DescriptionParameter = unt_Description != null ?
                new ObjectParameter("unt_Description", unt_Description) :
                new ObjectParameter("unt_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Insert_Unite_Soutien", unt_IDParameter, unt_UniteParameter, vil_IDParameter, unt_DescriptionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Unite_Soutien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Unite_Soutien");
        }
    
        public virtual ObjectResult<Search_Unite_Soutien_Result> Search_Unite_Soutien(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Unite_Soutien_Result>("Search_Unite_Soutien", searchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Update_Unite_Soutien(Nullable<int> unt_ID, string unt_Unite, Nullable<int> vil_ID, string unt_Description)
        {
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            var unt_UniteParameter = unt_Unite != null ?
                new ObjectParameter("unt_Unite", unt_Unite) :
                new ObjectParameter("unt_Unite", typeof(string));
    
            var vil_IDParameter = vil_ID.HasValue ?
                new ObjectParameter("vil_ID", vil_ID) :
                new ObjectParameter("vil_ID", typeof(int));
    
            var unt_DescriptionParameter = unt_Description != null ?
                new ObjectParameter("unt_Description", unt_Description) :
                new ObjectParameter("unt_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Update_Unite_Soutien", unt_IDParameter, unt_UniteParameter, vil_IDParameter, unt_DescriptionParameter);
        }
    
        public virtual ObjectResult<Unite_Soutien> Show_Unite_Soutien_By_ID(Nullable<int> unt_ID)
        {
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Unite_Soutien>("Show_Unite_Soutien_By_ID", unt_IDParameter);
        }
    
        public virtual ObjectResult<Unite_Soutien> Show_Unite_Soutien_By_ID(Nullable<int> unt_ID, MergeOption mergeOption)
        {
            var unt_IDParameter = unt_ID.HasValue ?
                new ObjectParameter("unt_ID", unt_ID) :
                new ObjectParameter("unt_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Unite_Soutien>("Show_Unite_Soutien_By_ID", mergeOption, unt_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Pneu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Pneu");
        }
    
        public virtual ObjectResult<Search_Bon_Entree_Result> Search_Bon_Entree(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Entree_Result>("Search_Bon_Entree", searchParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Bon_Entree(Nullable<bool> be_Historique)
        {
            var be_HistoriqueParameter = be_Historique.HasValue ?
                new ObjectParameter("be_Historique", be_Historique) :
                new ObjectParameter("be_Historique", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Bon_Entree", be_HistoriqueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Bon_Entree_Article(Nullable<bool> be_A_Historique)
        {
            var be_A_HistoriqueParameter = be_A_Historique.HasValue ?
                new ObjectParameter("be_A_Historique", be_A_Historique) :
                new ObjectParameter("be_A_Historique", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Bon_Entree_Article", be_A_HistoriqueParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Entree_Article_Result> Search_Bon_Entree_Article(string search, Nullable<int> be_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Entree_Article_Result>("Search_Bon_Entree_Article", searchParameter, be_IDParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Entree_Article_H_Result> Search_Bon_Entree_Article_H(string search, Nullable<int> be_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var be_IDParameter = be_ID.HasValue ?
                new ObjectParameter("be_ID", be_ID) :
                new ObjectParameter("be_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Entree_Article_H_Result>("Search_Bon_Entree_Article_H", searchParameter, be_IDParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Entree_H_Result> Search_Bon_Entree_H(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Entree_H_Result>("Search_Bon_Entree_H", searchParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Retour_Result> Search_Bon_Retour(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Retour_Result>("Search_Bon_Retour", searchParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Retour_Article_Result> Search_Bon_Retour_Article(string search, Nullable<int> br_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Retour_Article_Result>("Search_Bon_Retour_Article", searchParameter, br_IDParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Retour_Article_H_Result> Search_Bon_Retour_Article_H(string search, Nullable<int> br_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var br_IDParameter = br_ID.HasValue ?
                new ObjectParameter("br_ID", br_ID) :
                new ObjectParameter("br_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Retour_Article_H_Result>("Search_Bon_Retour_Article_H", searchParameter, br_IDParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Retour_H_Result> Search_Bon_Retour_H(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Retour_H_Result>("Search_Bon_Retour_H", searchParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Sortie_Result> Search_Bon_Sortie(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Sortie_Result>("Search_Bon_Sortie", searchParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Sortie_Article_Result> Search_Bon_Sortie_Article(string search, Nullable<int> bs_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Sortie_Article_Result>("Search_Bon_Sortie_Article", searchParameter, bs_IDParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Sortie_Article_H_Result> Search_Bon_Sortie_Article_H(string search, Nullable<int> bs_ID)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var bs_IDParameter = bs_ID.HasValue ?
                new ObjectParameter("bs_ID", bs_ID) :
                new ObjectParameter("bs_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Sortie_Article_H_Result>("Search_Bon_Sortie_Article_H", searchParameter, bs_IDParameter);
        }
    
        public virtual ObjectResult<Search_Bon_Sortie_H_Result> Search_Bon_Sortie_H(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Bon_Sortie_H_Result>("Search_Bon_Sortie_H", searchParameter);
        }
    
        public virtual int Historique_Bon_Entree_Article(Nullable<int> be_A_ID)
        {
            var be_A_IDParameter = be_A_ID.HasValue ?
                new ObjectParameter("be_A_ID", be_A_ID) :
                new ObjectParameter("be_A_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Historique_Bon_Entree_Article", be_A_IDParameter);
        }
    }
}
