//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int opera_ID { get; set; }
        public Nullable<System.DateTime> opera_Date { get; set; }
        public Nullable<int> pne_ID { get; set; }
        public string opera_Type { get; set; }
        public Nullable<int> opera_Qte { get; set; }
        public Nullable<int> bon_ID { get; set; }
        public Nullable<int> bs_A_ID { get; set; }
        public Nullable<int> be_A_ID { get; set; }
        public Nullable<int> br_A_ID { get; set; }
    
        public virtual Pneu Pneu { get; set; }
    }
}
