//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pneu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pneu()
        {
            this.Bon_Entree_Article = new HashSet<Bon_Entree_Article>();
            this.Operation = new HashSet<Operation>();
            this.Bon_Sortie_Article = new HashSet<Bon_Sortie_Article>();
            this.Bon_Retour_Article = new HashSet<Bon_Retour_Article>();
        }
    
        public int pne_ID { get; set; }
        public string pne_Designation { get; set; }
        public string pne_Marque { get; set; }
        public Nullable<System.DateTime> pne_Date_Production { get; set; }
        public string pne_Observation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Entree_Article> Bon_Entree_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operation> Operation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Sortie_Article> Bon_Sortie_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Retour_Article> Bon_Retour_Article { get; set; }
    }
}
