//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Representant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Representant()
        {
            this.Bon_Entree = new HashSet<Bon_Entree>();
        }
    
        public int rep_ID { get; set; }
        public Nullable<int> frns_ID { get; set; }
        public string rep_Nom { get; set; }
        public string rep_Prenom { get; set; }
        public string rep_Cin { get; set; }
        public string rep_Tele { get; set; }
        public string rep_Observation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bon_Entree> Bon_Entree { get; set; }
        public virtual Fournisseur Fournisseur { get; set; }
    }
}
